# Exercise Set 5

Below are five problems, each worth 1 point. These problems are interleaved with short tutorials on Python. This assignment will be autograded to ensure a quick turnaround. After several of the problems, there are tests associated with your answer which will help you determine if you have solved the problem correctly. If you can run the cell after your answer and not get any errors, then you very likely have gotten the question right. If you have errors, hopefully the error will help you identify the mistake. However, for some questions that ask for information, the grading cell will not tell you whether or not you got it correct (there is no way to do so without giving away the answer). It will tell you whether or not your formatting is correct.

Note that just because you don't get errors on the questions that do check your answer doesn't mean that you got the question correct. I have some additional tests held back that I do not show here, though if you pass the ones shown, you will likely pass those as well.

When you are done with the assignment, you should save this notebook manually by clicking on the save button in the toolbar (the floppy disk icon). **Do not rely on autosave. Save manually!** Ensure that you have not renamed the file. **The autograder that is used to grade this notebook requires that the file be named `Exercise_V.ipynb`.** Once you save the notebook, follow the instructions in the `README.md` file to submit the assignment.

Also, do not remove any datasets from the folder before downloading. You should download the folder exactly as is.

Finally, you are encouraged to add new cells as you go through the notebook and experiment. Any cell that should not be copied or deleted is marked as such. As long as you don't copy or delete the cells marked as such, then you should feel free to experiment as much as you would like with this notebook.

## Pandas DataFrames

In this exercise, we will primarily be looking at how to manipulate data within a pandas dataframe. Some of this you will have seen before in starter code, but hopefully you will develop a deeper understanding and appreciation for how to manipulate data in Python. First, we will import pandas and call it `pd` (giving us access to all of the pandas functions by writing `pd.FUNCTION`).

In [19]:
import pandas as pd

I am deeply indebted to open source material available at a few places. The list (not exhaustive) of sources is the following:

  1. [Python Pandas Tutorial: A Complete Introduction for Beginners](https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/). A large number of the examples was copied verbatim from here.
  2. [Pandas Exercises](https://github.com/guipsamora/pandas_exercises). A GitHub repository that provides a lot of examples around using Pandas. Some of the exercises were adapted from these examples, so do not use this as a resource until after submitting this and the next exercise sets.

## Problem Dataset - Chipotle Orders

In this assignment's questions, we are going to be analyzing some data from orders at Chipotle. You can read it in with the following cell. Notice the `sep = '\t'`. This is because the data set is tab seperated, not comma separated as we are used to.

Note that the below cell drops the duplicate rows, and it creates a new column called `item_price_number`. These were transformations to the dataset that were done in Exercise III. If you would like to familiarize yourself with these steps, you are encouraged to go back to Exercise III.

In [20]:
chipo = pd.read_csv("chipotle.tsv", sep = '\t')

chipo.drop_duplicates(inplace=True)

def price_to_float(price):
    return float(price[1:-1])

chipo['item_price_number'] = chipo['item_price'].apply(price_to_float)

You should spend some time familiarizing yourself with the data.

In [21]:
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  \
0                                                NaN     $2.39    
1                                       [Clementine]     $3.39    
2                                            [Apple]     $3.39    
3                                                NaN     $2.39    
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98    

   item_price_number  
0               2.39  
1               3.39  
2               3.39  
3               2.39  
4              16.98

This data set is broken up by `order_id` which corresponds to a particular order, and then within each order, there may be multiple items. The particular items are indicated by `item_name`, and any choices associated with those items are indicated by `choice_description` (e.g. the second item in `order_id=1` is an "Izze" drink with "Clementine" flavor). Additionally, there is the `item_price` for each order and the `quantity` of the item ordered. Be careful with the `item_price` as it is not the price for the item, it is the price for the item times the number of items ordered. You can see this in row 4 where `order_id=2` orders 2 chicken bowls for `$16.98` where a single chicken bowl would be half of that.

In [22]:
chipo.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1228
item_price               0
item_price_number        0
dtype: int64

## Advanced Pandas Dataframes

We will be looking at movies from IMDB. This data set is on Kaggle and you can find the original [here](https://www.kaggle.com/PromptCloudHQ/imdb-data/download).

In [23]:
movies_df = pd.read_csv("IMDB-Movie-Data.csv", index_col="Title")

Note that we just specified a particular column of the csv (in this case, the one called "Title") as the index.

In [24]:
movies_df

Rank                     Genre  \
Title                                                     
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi   
Prometheus                  2  Adventure,Mystery,Sci-Fi   
Split                       3           Horror,Thriller   
Sing                        4   Animation,Comedy,Family   
Suicide Squad               5  Action,Adventure,Fantasy   
...                       ...                       ...   
Secret in Their Eyes      996       Crime,Drama,Mystery   
Hostel: Part II           997                    Horror   
Step Up 2: The Streets    998       Drama,Music,Romance   
Search Party              999          Adventure,Comedy   
Nine Lives               1000     Comedy,Family,Fantasy   

                                                               Description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   
...                                                                    ...   
Secret in Their Eyes     A tight-knit team of rising investigators, alo...   
Hostel: Part II          Three American college students studying abroa...   
Step Up 2: The Streets   Romantic sparks occur between two dance studen...   
Search Party             A pair of friends embark on a mission to reuni...   
Nine Lives               A stuffy businessman finds himself trapped ins...   

                                     Director  \
Title                                           
Guardians of the Galaxy            James Gunn   
Prometheus                       Ridley Scott   
Split                      M. Night Shyamalan   
Sing                     Christophe Lourdelet   
Suicide Squad                      David Ayer   
...                                       ...   
Secret in Their Eyes                Billy Ray   
Hostel: Part II                      Eli Roth   
Step Up 2: The Streets             Jon M. Chu   
Search Party                   Scot Armstrong   
Nine Lives                   Barry Sonnenfeld   

                                                                    Actors  \
Title                                                                        
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...   
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...   
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...   
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...   
...                                                                    ...   
Secret in Their Eyes     Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...   
Hostel: Part II          Lauren German, Heather Matarazzo, Bijou Philli...   
Step Up 2: The Streets   Robert Hoffman, Briana Evigan, Cassie Ventura,...   
Search Party             Adam Pally, T.J. Miller, Thomas Middleditch,Sh...   
Nine Lives               Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...   

                         Year  Runtime (Minutes)  Rating   Votes  \
Title                                                              
Guardians of the Galaxy  2014                121     8.1  757074   
Prometheus               2012                124     7.0  485820   
Split                    2016                117     7.3  157606   
Sing                     2016                108     7.2   60545   
Suicide Squad            2016                123     6.2  393727   
...                       ...                ...     ...     ...   
Secret in Their Eyes     2015                

What about our columns? We can see a full list with the following.

In [25]:
movies_df.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

Often times it would be nice not to have spaces in the column names, so let's get rid of them.

In [26]:
movies_df.rename(columns={
        'Runtime (Minutes)': 'Runtime', 
        'Revenue (Millions)': 'Revenue_millions'
    }, inplace=True)

In [27]:
movies_df.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year', 'Runtime',
       'Rating', 'Votes', 'Revenue_millions', 'Metascore'],
      dtype='object')

That's better, and we remembered to do `inplace=True` this time.

Sometimes we would like everything to be lower case as well, and that would be a pain to write it all out. However, we can use list comprehension to make it easy. First, let's get the lower case names.

In [28]:
lowercase_columns = [col.lower() for col in movies_df.columns]

In [29]:
lowercase_columns

['rank',
 'genre',
 'description',
 'director',
 'actors',
 'year',
 'runtime',
 'rating',
 'votes',
 'revenue_millions',
 'metascore']

Now, we can just set the columns of `movies_df` equal to this.

In [30]:
movies_df.columns = lowercase_columns

In [31]:
movies_df

rank                     genre  \
Title                                                     
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi   
Prometheus                  2  Adventure,Mystery,Sci-Fi   
Split                       3           Horror,Thriller   
Sing                        4   Animation,Comedy,Family   
Suicide Squad               5  Action,Adventure,Fantasy   
...                       ...                       ...   
Secret in Their Eyes      996       Crime,Drama,Mystery   
Hostel: Part II           997                    Horror   
Step Up 2: The Streets    998       Drama,Music,Romance   
Search Party              999          Adventure,Comedy   
Nine Lives               1000     Comedy,Family,Fantasy   

                                                               description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   
...                                                                    ...   
Secret in Their Eyes     A tight-knit team of rising investigators, alo...   
Hostel: Part II          Three American college students studying abroa...   
Step Up 2: The Streets   Romantic sparks occur between two dance studen...   
Search Party             A pair of friends embark on a mission to reuni...   
Nine Lives               A stuffy businessman finds himself trapped ins...   

                                     director  \
Title                                           
Guardians of the Galaxy            James Gunn   
Prometheus                       Ridley Scott   
Split                      M. Night Shyamalan   
Sing                     Christophe Lourdelet   
Suicide Squad                      David Ayer   
...                                       ...   
Secret in Their Eyes                Billy Ray   
Hostel: Part II                      Eli Roth   
Step Up 2: The Streets             Jon M. Chu   
Search Party                   Scot Armstrong   
Nine Lives                   Barry Sonnenfeld   

                                                                    actors  \
Title                                                                        
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...   
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...   
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...   
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...   
...                                                                    ...   
Secret in Their Eyes     Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...   
Hostel: Part II          Lauren German, Heather Matarazzo, Bijou Philli...   
Step Up 2: The Streets   Robert Hoffman, Briana Evigan, Cassie Ventura,...   
Search Party             Adam Pally, T.J. Miller, Thomas Middleditch,Sh...   
Nine Lives               Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...   

                         year  runtime  rating   votes  revenue_millions  \
Title                                                                      
Guardians of the Galaxy  2014      121     8.1  757074            333.13   
Prometheus               2012      124     7.0  485820            126.46   
Split                    2016      117     7.3  157606            138.12   
Sing                     2016      108     7.2   60545            270.32   
Suicide Squad            2016      123     6.2  393727            325.02   
...                       ...      ...     ...     ...   

Now, they are all lowercase.

## Working with Missing Values

While we've seen how to impute values in other assignments, sometimes it's good to clean up missing values straight in the dataframe. Let's see if we have any.

In [32]:
movies_df.isnull()

rank  genre  description  director  actors   year  \
Title                                                                         
Guardians of the Galaxy  False  False        False     False   False  False   
Prometheus               False  False        False     False   False  False   
Split                    False  False        False     False   False  False   
Sing                     False  False        False     False   False  False   
Suicide Squad            False  False        False     False   False  False   
...                        ...    ...          ...       ...     ...    ...   
Secret in Their Eyes     False  False        False     False   False  False   
Hostel: Part II          False  False        False     False   False  False   
Step Up 2: The Streets   False  False        False     False   False  False   
Search Party             False  False        False     False   False  False   
Nine Lives               False  False        False     False   False  False   

                         runtime  rating  votes  revenue_millions  metascore  
Title                                                                         
Guardians of the Galaxy    False   False  False             False      False  
Prometheus                 False   False  False             False      False  
Split                      False   False  False             False      False  
Sing                       False   False  False             False      False  
Suicide Squad              False   False  False             False      False  
...                          ...     ...    ...               ...        ...  
Secret in Their Eyes       False   False  False              True      False  
Hostel: Part II            False   False  False             False      False  
Step Up 2: The Streets     False   False  False             False      False  
Search Party               False   False  False              True      False  
Nine Lives                 False   False  False             False      False  

[1000 rows x 11 columns]

That's not quite the best way to look at it `.isnull()` tells us using either `True` or `False` whether any particular values is missing. We'd really like to summarize over columns. We can use `.sum()` for that. This is also an example of chaining methods together. We often end up doing this with Pandas. The first method summarizes the data in one way, and then we summarize the summary.

In [33]:
movies_df.isnull().sum()

rank                  0
genre                 0
description           0
director              0
actors                0
year                  0
runtime               0
rating                0
votes                 0
revenue_millions    128
metascore            64
dtype: int64

We can find the total number of null values using a double application of the `.sum()` method, once for all of the rows in each column and then once to sum over all of the columns.

In [34]:
movies_df.isnull().sum().sum()

192

### Problem #1 - 1 point

How many null values are there altogether in the Chipotle dataset? Store your answer in a variable called `null_values`. I.e, your answer should look like
``` python
null_values = x
```
where x is a numeric value. The grade will not tell you whether not you are right, but it will tell you whether your answer is in the correct format.

In [44]:
import pandas as pd
import numbers
chipotle_data = pd.read_csv('chipotle.tsv', delimiter='\t')
null_values = chipotle_data.isnull().sum().sum()
print(null_values)
assert isinstance(null_values, numbers.Number)

1246


In [45]:
# THIS IS A GRADING CELL. DO NOT EDIT.
# This cell will not tell you whether or not your answer is right.
# If you have not assigned something to the variable null_values or you have not assigned a string,
# you will get an error, but if you just get the question wrong,
# you will not necessarily get an error.
from nose.tools import assert_equal, assert_true
import numbers
print(null_values)
assert_true(isinstance(null_values, numbers.Number))

1246


Now we can see that we are missing some `revenue_millions` and some `metascore` data. Let's just get rid of those rows that have missing values.

In [46]:
movies_df.dropna()

rank                     genre  \
Title                                                      
Guardians of the Galaxy      1   Action,Adventure,Sci-Fi   
Prometheus                   2  Adventure,Mystery,Sci-Fi   
Split                        3           Horror,Thriller   
Sing                         4   Animation,Comedy,Family   
Suicide Squad                5  Action,Adventure,Fantasy   
...                        ...                       ...   
Resident Evil: Afterlife   994   Action,Adventure,Horror   
Project X                  995                    Comedy   
Hostel: Part II            997                    Horror   
Step Up 2: The Streets     998       Drama,Music,Romance   
Nine Lives                1000     Comedy,Family,Fantasy   

                                                                description  \
Title                                                                         
Guardians of the Galaxy   A group of intergalactic criminals are forced ...   
Prometheus                Following clues to the origin of mankind, a te...   
Split                     Three girls are kidnapped by a man with a diag...   
Sing                      In a city of humanoid animals, a hustling thea...   
Suicide Squad             A secret government agency recruits some of th...   
...                                                                     ...   
Resident Evil: Afterlife  While still out to destroy the evil Umbrella C...   
Project X                 3 high school seniors throw a birthday party t...   
Hostel: Part II           Three American college students studying abroa...   
Step Up 2: The Streets    Romantic sparks occur between two dance studen...   
Nine Lives                A stuffy businessman finds himself trapped ins...   

                                      director  \
Title                                            
Guardians of the Galaxy             James Gunn   
Prometheus                        Ridley Scott   
Split                       M. Night Shyamalan   
Sing                      Christophe Lourdelet   
Suicide Squad                       David Ayer   
...                                        ...   
Resident Evil: Afterlife    Paul W.S. Anderson   
Project X                      Nima Nourizadeh   
Hostel: Part II                       Eli Roth   
Step Up 2: The Streets              Jon M. Chu   
Nine Lives                    Barry Sonnenfeld   

                                                                     actors  \
Title                                                                         
Guardians of the Galaxy   Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...   
Prometheus                Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Split                     James McAvoy, Anya Taylor-Joy, Haley Lu Richar...   
Sing                      Matthew McConaughey,Reese Witherspoon, Seth Ma...   
Suicide Squad             Will Smith, Jared Leto, Margot Robbie, Viola D...   
...                                                                     ...   
Resident Evil: Afterlife  Milla Jovovich, Ali Larter, Wentworth Miller,K...   
Project X                 Thomas Mann, Oliver Cooper, Jonathan Daniel Br...   
Hostel: Part II           Lauren German, Heather Matarazzo, Bijou Philli...   
Step Up 2: The Streets    Robert Hoffman, Briana Evigan, Cassie Ventura,...   
Nine Lives                Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...   

                          year  runtime  rating   votes  revenue_millions  \
Title                                                                       
Guardians of the Galaxy   2014      121     8.1  757074            333.13   
Prometheus                2012      124     7.0  485820            126.46   
Split                     2016      117     7.3  157606            138.12   
Sing                      2016      108     7.2   60545            270.32   
Suicide Squad             2016      123     6.2  393727            325.02   

We didn't do `inplace=True`, so this won't stick to our original `movies_df` dataframe, but we can tell that it got rid of 162 rows. Maybe instead of getting rid of the rows, we would have preferred to get rid of the columns that have missing data. We can do that like this.

In [47]:
movies_df.dropna(axis=1)

rank                     genre  \
Title                                                     
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi   
Prometheus                  2  Adventure,Mystery,Sci-Fi   
Split                       3           Horror,Thriller   
Sing                        4   Animation,Comedy,Family   
Suicide Squad               5  Action,Adventure,Fantasy   
...                       ...                       ...   
Secret in Their Eyes      996       Crime,Drama,Mystery   
Hostel: Part II           997                    Horror   
Step Up 2: The Streets    998       Drama,Music,Romance   
Search Party              999          Adventure,Comedy   
Nine Lives               1000     Comedy,Family,Fantasy   

                                                               description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   
...                                                                    ...   
Secret in Their Eyes     A tight-knit team of rising investigators, alo...   
Hostel: Part II          Three American college students studying abroa...   
Step Up 2: The Streets   Romantic sparks occur between two dance studen...   
Search Party             A pair of friends embark on a mission to reuni...   
Nine Lives               A stuffy businessman finds himself trapped ins...   

                                     director  \
Title                                           
Guardians of the Galaxy            James Gunn   
Prometheus                       Ridley Scott   
Split                      M. Night Shyamalan   
Sing                     Christophe Lourdelet   
Suicide Squad                      David Ayer   
...                                       ...   
Secret in Their Eyes                Billy Ray   
Hostel: Part II                      Eli Roth   
Step Up 2: The Streets             Jon M. Chu   
Search Party                   Scot Armstrong   
Nine Lives                   Barry Sonnenfeld   

                                                                    actors  \
Title                                                                        
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...   
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...   
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...   
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...   
...                                                                    ...   
Secret in Their Eyes     Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...   
Hostel: Part II          Lauren German, Heather Matarazzo, Bijou Philli...   
Step Up 2: The Streets   Robert Hoffman, Briana Evigan, Cassie Ventura,...   
Search Party             Adam Pally, T.J. Miller, Thomas Middleditch,Sh...   
Nine Lives               Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...   

                         year  runtime  rating   votes  
Title                                                   
Guardians of the Galaxy  2014      121     8.1  757074  
Prometheus               2012      124     7.0  485820  
Split                    2016      117     7.3  157606  
Sing                     2016      108     7.2   60545  
Suicide Squad            2016      123     6.2  393727  
...                       ...      ...     ...     ...  
Secret in Their Eyes     2015      111     6.2   27585  
Hostel: Part II          2007       94     5.5   73152  
Step Up 2: The Stre

Remember, `axis=0` means the rows of a dataframe, and `axis=1` means the columns of a dataframe whenever we are applying things like `.dropna()`. We see that we ended up with fewer columns (we got rid of the columns `revenue_millions` and `metascore`), but have all of our rows.

Of course, we could have imputed these values as well, and we've seen how to do that with `sklearn` functions. We can do something similar in pandas, but I don't recommend it.

## Sorting the Data

Often times we want to sort the dataframe in order to answer some questions. We can do that with the `.sort_values()` method, where we tell it `by` which column.

In [48]:
movies_df.sort_values(by = "rating")

rank                     genre  \
Title                                                     
Disaster Movie            830                    Comedy   
Don't Fuck in the Woods    43                    Horror   
Dragonball Evolution      872  Action,Adventure,Fantasy   
Tall Men                  648   Fantasy,Horror,Thriller   
Wrecker                   969    Action,Horror,Thriller   
...                       ...                       ...   
Interstellar               37    Adventure,Drama,Sci-Fi   
The Intouchables          250    Biography,Comedy,Drama   
Dangal                    118    Action,Biography,Drama   
Inception                  81   Action,Adventure,Sci-Fi   
The Dark Knight            55        Action,Crime,Drama   

                                                               description  \
Title                                                                        
Disaster Movie           Over the course of one evening, an unsuspectin...   
Don't Fuck in the Woods  A group of friends are going on a camping trip...   
Dragonball Evolution     The young warrior Son Goku sets out on a quest...   
Tall Men                 A challenged man is stalked by tall phantoms i...   
Wrecker                  Best friends Emily and Lesley go on a road tri...   
...                                                                    ...   
Interstellar             A team of explorers travel through a wormhole ...   
The Intouchables         After he becomes a quadriplegic from a paragli...   
Dangal                   Former wrestler Mahavir Singh Phogat and his t...   
Inception                A thief, who steals corporate secrets through ...   
The Dark Knight          When the menace known as the Joker wreaks havo...   

                                  director  \
Title                                        
Disaster Movie             Jason Friedberg   
Don't Fuck in the Woods      Shawn Burkett   
Dragonball Evolution            James Wong   
Tall Men                 Jonathan Holbrook   
Wrecker                     Micheal Bafaro   
...                                    ...   
Interstellar             Christopher Nolan   
The Intouchables           Olivier Nakache   
Dangal                       Nitesh Tiwari   
Inception                Christopher Nolan   
The Dark Knight          Christopher Nolan   

                                                                    actors  \
Title                                                                        
Disaster Movie           Carmen Electra, Vanessa Lachey,Nicole Parker, ...   
Don't Fuck in the Woods  Brittany Blanton, Ayse Howard, Roman Jossart,N...   
Dragonball Evolution     Justin Chatwin, James Marsters, Yun-Fat Chow, ...   
Tall Men                 Dan Crisafulli, Kay Whitney, Richard Garcia, P...   
Wrecker                  Anna Hutchison, Andrea Whitburn, Jennifer Koen...   
...                                                                    ...   
Interstellar             Matthew McConaughey, Anne Hathaway, Jessica Ch...   
The Intouchables         François Cluzet, Omar Sy, Anne Le Ny, Audrey F...   
Dangal                   Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...   
Inception                Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...   
The Dark Knight          Christian Bale, Heath Ledger, Aaron Eckhart,Mi...   

                         year  runtime  rating    votes  revenue_millions  \
Title                                                                       
Disaster Movie           2008       87     1.9    77207             14.17   
Don't Fuck in the Woods  2016       73     2.7      496               NaN   
Dragonball Evolution     2009       85     2.7    59512              9.35   
Tall Men                 2016      133     3.2      173               NaN   
Wrecker                  2015       83     3.5     1210               NaN   
...                       ...      ...     ...      ...               ...   
Interstellar

We may want to have it sorted descending instead.

In [49]:
movies_df.sort_values(by = "rating", ascending=False)

rank                     genre  \
Title                                                     
The Dark Knight            55        Action,Crime,Drama   
Inception                  81   Action,Adventure,Sci-Fi   
Dangal                    118    Action,Biography,Drama   
Interstellar               37    Adventure,Drama,Sci-Fi   
Kimi no na wa              97   Animation,Drama,Fantasy   
...                       ...                       ...   
Wrecker                   969    Action,Horror,Thriller   
Tall Men                  648   Fantasy,Horror,Thriller   
Dragonball Evolution      872  Action,Adventure,Fantasy   
Don't Fuck in the Woods    43                    Horror   
Disaster Movie            830                    Comedy   

                                                               description  \
Title                                                                        
The Dark Knight          When the menace known as the Joker wreaks havo...   
Inception                A thief, who steals corporate secrets through ...   
Dangal                   Former wrestler Mahavir Singh Phogat and his t...   
Interstellar             A team of explorers travel through a wormhole ...   
Kimi no na wa            Two strangers find themselves linked in a biza...   
...                                                                    ...   
Wrecker                  Best friends Emily and Lesley go on a road tri...   
Tall Men                 A challenged man is stalked by tall phantoms i...   
Dragonball Evolution     The young warrior Son Goku sets out on a quest...   
Don't Fuck in the Woods  A group of friends are going on a camping trip...   
Disaster Movie           Over the course of one evening, an unsuspectin...   

                                  director  \
Title                                        
The Dark Knight          Christopher Nolan   
Inception                Christopher Nolan   
Dangal                       Nitesh Tiwari   
Interstellar             Christopher Nolan   
Kimi no na wa               Makoto Shinkai   
...                                    ...   
Wrecker                     Micheal Bafaro   
Tall Men                 Jonathan Holbrook   
Dragonball Evolution            James Wong   
Don't Fuck in the Woods      Shawn Burkett   
Disaster Movie             Jason Friedberg   

                                                                    actors  \
Title                                                                        
The Dark Knight          Christian Bale, Heath Ledger, Aaron Eckhart,Mi...   
Inception                Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...   
Dangal                   Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...   
Interstellar             Matthew McConaughey, Anne Hathaway, Jessica Ch...   
Kimi no na wa            Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...   
...                                                                    ...   
Wrecker                  Anna Hutchison, Andrea Whitburn, Jennifer Koen...   
Tall Men                 Dan Crisafulli, Kay Whitney, Richard Garcia, P...   
Dragonball Evolution     Justin Chatwin, James Marsters, Yun-Fat Chow, ...   
Don't Fuck in the Woods  Brittany Blanton, Ayse Howard, Roman Jossart,N...   
Disaster Movie           Carmen Electra, Vanessa Lachey,Nicole Parker, ...   

                         year  runtime  rating    votes  revenue_millions  \
Title                                                                       
The Dark Knight          2008      152     9.0  1791916            533.32   
Inception                2010      148     8.8  1583625            292.57   
Dangal                   2016      161     8.8    48969             11.15   
Interstellar             2014      169     8.6  1047747            187.99   
Kimi no na wa            2016      106     8.6    34110              4.68   
...                       ...      ...     ...      ...               ...   
Wrecker     

Notice that just like before, we haven't actually changed the underlying dataframe because we didn't sort `inplace`.

In [50]:
movies_df

rank                     genre  \
Title                                                     
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi   
Prometheus                  2  Adventure,Mystery,Sci-Fi   
Split                       3           Horror,Thriller   
Sing                        4   Animation,Comedy,Family   
Suicide Squad               5  Action,Adventure,Fantasy   
...                       ...                       ...   
Secret in Their Eyes      996       Crime,Drama,Mystery   
Hostel: Part II           997                    Horror   
Step Up 2: The Streets    998       Drama,Music,Romance   
Search Party              999          Adventure,Comedy   
Nine Lives               1000     Comedy,Family,Fantasy   

                                                               description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   
...                                                                    ...   
Secret in Their Eyes     A tight-knit team of rising investigators, alo...   
Hostel: Part II          Three American college students studying abroa...   
Step Up 2: The Streets   Romantic sparks occur between two dance studen...   
Search Party             A pair of friends embark on a mission to reuni...   
Nine Lives               A stuffy businessman finds himself trapped ins...   

                                     director  \
Title                                           
Guardians of the Galaxy            James Gunn   
Prometheus                       Ridley Scott   
Split                      M. Night Shyamalan   
Sing                     Christophe Lourdelet   
Suicide Squad                      David Ayer   
...                                       ...   
Secret in Their Eyes                Billy Ray   
Hostel: Part II                      Eli Roth   
Step Up 2: The Streets             Jon M. Chu   
Search Party                   Scot Armstrong   
Nine Lives                   Barry Sonnenfeld   

                                                                    actors  \
Title                                                                        
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...   
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...   
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...   
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...   
...                                                                    ...   
Secret in Their Eyes     Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...   
Hostel: Part II          Lauren German, Heather Matarazzo, Bijou Philli...   
Step Up 2: The Streets   Robert Hoffman, Briana Evigan, Cassie Ventura,...   
Search Party             Adam Pally, T.J. Miller, Thomas Middleditch,Sh...   
Nine Lives               Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...   

                         year  runtime  rating   votes  revenue_millions  \
Title                                                                      
Guardians of the Galaxy  2014      121     8.1  757074            333.13   
Prometheus               2012      124     7.0  485820            126.46   
Split                    2016      117     7.3  157606            138.12   
Sing                     2016      108     7.2   60545            270.32   
Suicide Squad            2016      123     6.2  393727            325.02   
...                       ...      ...     ...     ...   

We can also sort by two dimensions. The following sorts first by year, and then by rating.

In [51]:
movies_df.sort_values(by = ["year", "rating"], ascending=False)

rank                    genre  \
Title                                                                  
Dangal                                  118   Action,Biography,Drama   
Kimi no na wa                            97  Animation,Drama,Fantasy   
Koe no katachi                          862  Animation,Drama,Romance   
La La Land                                7       Comedy,Drama,Music   
Paint It Black                          479                    Drama   
...                                     ...                      ...   
Superman Returns                        925  Action,Adventure,Sci-Fi   
The Fast and the Furious: Tokyo Drift   309    Action,Crime,Thriller   
The Break-Up                            551     Comedy,Drama,Romance   
Lady in the Water                       774    Drama,Fantasy,Mystery   
Snakes on a Plane                       902   Action,Adventure,Crime   

                                                                             description  \
Title                                                                                      
Dangal                                 Former wrestler Mahavir Singh Phogat and his t...   
Kimi no na wa                          Two strangers find themselves linked in a biza...   
Koe no katachi                         The story revolves around Nishimiya Shoko, a g...   
La La Land                             A jazz pianist falls for an aspiring actress i...   
Paint It Black                         A young woman attempts to deal with the death ...   
...                                                                                  ...   
Superman Returns                       Superman reappears after a long absence, but i...   
The Fast and the Furious: Tokyo Drift  A teenager becomes a major competitor in the w...   
The Break-Up                           In a bid to keep their luxurious condo from th...   
Lady in the Water                      Apartment building superintendent Cleveland He...   
Snakes on a Plane                      An FBI agent takes on a plane full of deadly a...   

                                                 director  \
Title                                                       
Dangal                                      Nitesh Tiwari   
Kimi no na wa                              Makoto Shinkai   
Koe no katachi                               Naoko Yamada   
La La Land                                Damien Chazelle   
Paint It Black                              Amber Tamblyn   
...                                                   ...   
Superman Returns                             Bryan Singer   
The Fast and the Furious: Tokyo Drift          Justin Lin   
The Break-Up                                  Peyton Reed   
Lady in the Water                      M. Night Shyamalan   
Snakes on a Plane                          David R. Ellis   

                                                                                  actors  \
Title                                                                                      
Dangal                                 Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...   
Kimi no na wa                          Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...   
Koe no katachi                            Miyu Irino, Saori Hayami, Aoi Yuki, Kenshô Ono   
La La Land                             Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....   
Paint It Black                         Alia Shawkat, Nancy Kwan, Annabelle Attanasio,...   
...                                                                                  ...   
Superman Returns                       Brandon Routh, Kevin Spacey, Kate Bosworth, Ja...   
The Fast and the Furious: Tokyo Drift  Lucas Black, Zachery Ty Bryan, Shad Moss, Dami...   
The Break-Up                           Jennifer Aniston, Vince Vaughn, Jon Favreau, J...   
Lady in the Water                      Paul Giamatti, Bryce Dallas Howard, Jeffrey Wr...   
Snakes 

### Problem #2 - 1 point

What item was ordered the most times in a single order? Remember, the `quantity` column is the number of times an item was ordered in a single order. The grade cell will not tell you whether or not you are right. Your answer should look like
``` python
most_single_ordered = "Item Name Typed Exactly"
```
With `Item Name Typed Exactly` replaced with the exact item name in quotes (and not indented obviously). I.e., if the item ordered the most times in a single order was `Nantucket Nectar`, then your answer would look like `most_single_ordered = "Nantucket Nectar"`.

In [56]:
import pandas as pd
chipotle_data = pd.read_csv('chipotle.tsv', delimiter='\t')
item_quantity = chipotle_data.groupby('item_name')['quantity'].sum()
most_single_ordered = item_quantity.idxmax()
print(most_single_ordered)

Chicken Bowl


In [57]:
# THIS IS A GRADING CELL. DO NOT EDIT.
# This cell will not tell you whether or not your answer is right.
# If you have not assigned something to the variable most_single_ordered or you have not assigned a string,
# you will get an error, but if you just get the question wrong,
# you will not necessarily get an error.
from nose.tools import assert_equal, assert_in
assert_equal(type(most_single_ordered), str)
print(most_single_ordered)

Chicken Bowl


## Summarizing the Data

There are a couple of ways we can use the DataFrame to summarize itself. In fact, we've been using these methods to build up our `summarize_dataframe` function (after this exercise, take a look at it and see if it makes more sense). The first is the `.describe()` method.

In [58]:
movies_df.describe()

rank         year      runtime       rating         votes  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1.000000e+03   
mean    500.500000  2012.783000   113.172000     6.723200  1.698083e+05   
std     288.819436     3.205962    18.810908     0.945429  1.887626e+05   
min       1.000000  2006.000000    66.000000     1.900000  6.100000e+01   
25%     250.750000  2010.000000   100.000000     6.200000  3.630900e+04   
50%     500.500000  2014.000000   111.000000     6.800000  1.107990e+05   
75%     750.250000  2016.000000   123.000000     7.400000  2.399098e+05   
max    1000.000000  2016.000000   191.000000     9.000000  1.791916e+06   

       revenue_millions   metascore  
count        872.000000  936.000000  
mean          82.956376   58.985043  
std          103.253540   17.194757  
min            0.000000   11.000000  
25%           13.270000   47.000000  
50%           47.985000   59.500000  
75%          113.715000   72.000000  
max          936.630000  100.000000

Note that the `.describe()` method only summarized the continous values. We can `.describe()` categorical values, but we have to call it on just the categorical values.

In [59]:
movies_df[['genre', 'description']].describe()

genre  \
count                      1000   
unique                      207   
top     Action,Adventure,Sci-Fi   
freq                         50   

                                              description  
count                                                1000  
unique                                               1000  
top     A group of intergalactic criminals are forced ...  
freq                                                    1

For a categorical value, we can tell the frequency of each category with `.value_counts()`. For a really long list (like `genre` which according to the above has 207 different values) we can use `.head()` to only get the top part by chaining methods together.

In [60]:
movies_df['genre'].value_counts().head(10)

genre
Action,Adventure,Sci-Fi       50
Drama                         48
Comedy,Drama,Romance          35
Comedy                        32
Drama,Romance                 31
Animation,Adventure,Comedy    27
Action,Adventure,Fantasy      27
Comedy,Drama                  27
Comedy,Romance                26
Crime,Drama,Thriller          24
Name: count, dtype: int64

For continuous variables, we can get the correlation as well. Note that we use `numeric_only=True` as part of the argument. This is necessary for operations on pandas dataframes that expect numeric values, but there is a mixture of numeric and categorical variables in the dataframe.

In [61]:
movies_df.corr(numeric_only=True)

rank      year   runtime    rating     votes  \
rank              1.000000 -0.261605 -0.221739 -0.219555 -0.283876   
year             -0.261605  1.000000 -0.164900 -0.211219 -0.411904   
runtime          -0.221739 -0.164900  1.000000  0.392214  0.407062   
rating           -0.219555 -0.211219  0.392214  1.000000  0.511537   
votes            -0.283876 -0.411904  0.407062  0.511537  1.000000   
revenue_millions -0.271592 -0.126790  0.267953  0.217654  0.639661   
metascore        -0.191869 -0.079305  0.211978  0.631897  0.325684   

                  revenue_millions  metascore  
rank                     -0.271592  -0.191869  
year                     -0.126790  -0.079305  
runtime                   0.267953   0.211978  
rating                    0.217654   0.631897  
votes                     0.639661   0.325684  
revenue_millions          1.000000   0.142397  
metascore                 0.142397   1.000000

## DataFrame Slicing, Dicing, and Extracting

We regularly only want to work with a subset of the data, either a set of columns or a set of rows. Fortunately, it is easy with DataFrames to get a subset. Let's start by pulling out a single column.

In [62]:
genre_col = movies_df['genre']

What did we actually get back?

In [63]:
type(genre_col)

pandas.core.series.Series

In [64]:
genre_col

Title
Guardians of the Galaxy     Action,Adventure,Sci-Fi
Prometheus                 Adventure,Mystery,Sci-Fi
Split                               Horror,Thriller
Sing                        Animation,Comedy,Family
Suicide Squad              Action,Adventure,Fantasy
                                     ...           
Secret in Their Eyes            Crime,Drama,Mystery
Hostel: Part II                              Horror
Step Up 2: The Streets          Drama,Music,Romance
Search Party                       Adventure,Comedy
Nine Lives                    Comedy,Family,Fantasy
Name: genre, Length: 1000, dtype: object

It's a Series! See, I told you that DataFrames were made up of Series.

If we want to get a DataFrame back, we need to give `movies_df` a _list_ of columns (it can be a list with a single item).

In [65]:
genre_df = movies_df[['genre']]

In [66]:
type(genre_df)

pandas.core.frame.DataFrame

In [67]:
genre_df

genre
Title                                            
Guardians of the Galaxy   Action,Adventure,Sci-Fi
Prometheus               Adventure,Mystery,Sci-Fi
Split                             Horror,Thriller
Sing                      Animation,Comedy,Family
Suicide Squad            Action,Adventure,Fantasy
...                                           ...
Secret in Their Eyes          Crime,Drama,Mystery
Hostel: Part II                            Horror
Step Up 2: The Streets        Drama,Music,Romance
Search Party                     Adventure,Comedy
Nine Lives                  Comedy,Family,Fantasy

[1000 rows x 1 columns]

If we are giving a list, we can give more columns.

In [68]:
subset_df = movies_df[['genre', 'rating']]

In [69]:
subset_df

genre  rating
Title                                                    
Guardians of the Galaxy   Action,Adventure,Sci-Fi     8.1
Prometheus               Adventure,Mystery,Sci-Fi     7.0
Split                             Horror,Thriller     7.3
Sing                      Animation,Comedy,Family     7.2
Suicide Squad            Action,Adventure,Fantasy     6.2
...                                           ...     ...
Secret in Their Eyes          Crime,Drama,Mystery     6.2
Hostel: Part II                            Horror     5.5
Step Up 2: The Streets        Drama,Music,Romance     6.2
Search Party                     Adventure,Comedy     5.6
Nine Lives                  Comedy,Family,Fantasy     5.3

[1000 rows x 2 columns]

For rows, we have two equivalent ways to get data. Both methods **loc**ate a row and return it.
  * `.loc` - **loc**ates by name
  * `.iloc` - **loc**ates by numerical **i**ndex
  
Let's get the data for the movie Prometheus.

In [70]:
prom = movies_df.loc["Prometheus"]

In [71]:
prom

rank                                                                2
genre                                        Adventure,Mystery,Sci-Fi
description         Following clues to the origin of mankind, a te...
director                                                 Ridley Scott
actors              Noomi Rapace, Logan Marshall-Green, Michael Fa...
year                                                             2012
runtime                                                           124
rating                                                            7.0
votes                                                          485820
revenue_millions                                               126.46
metascore                                                        65.0
Name: Prometheus, dtype: object

Alternatively, we can give it the row number. Remember, Prometheus is the second row in the DataFrame (and we start counting from 0).

In [72]:
prom = movies_df.iloc[1]

In [73]:
prom

rank                                                                2
genre                                        Adventure,Mystery,Sci-Fi
description         Following clues to the origin of mankind, a te...
director                                                 Ridley Scott
actors              Noomi Rapace, Logan Marshall-Green, Michael Fa...
year                                                             2012
runtime                                                           124
rating                                                            7.0
votes                                                          485820
revenue_millions                                               126.46
metascore                                                        65.0
Name: Prometheus, dtype: object

We can also get a range of rows, just like we can with a list. Let's look at a subset of the movies.

In [74]:
movie_subset = movies_df.loc['Prometheus':'Sing']

In [75]:
movie_subset

rank                     genre  \
Title                                        
Prometheus     2  Adventure,Mystery,Sci-Fi   
Split          3           Horror,Thriller   
Sing           4   Animation,Comedy,Family   

                                                  description  \
Title                                                           
Prometheus  Following clues to the origin of mankind, a te...   
Split       Three girls are kidnapped by a man with a diag...   
Sing        In a city of humanoid animals, a hustling thea...   

                        director  \
Title                              
Prometheus          Ridley Scott   
Split         M. Night Shyamalan   
Sing        Christophe Lourdelet   

                                                       actors  year  runtime  \
Title                                                                          
Prometheus  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012      124   
Split       James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016      117   
Sing        Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016      108   

            rating   votes  revenue_millions  metascore  
Title                                                    
Prometheus     7.0  485820            126.46       65.0  
Split          7.3  157606            138.12       62.0  
Sing           7.2   60545            270.32       59.0

In [76]:
movie_subset = movies_df.iloc[1:4]

In [77]:
movie_subset

rank                     genre  \
Title                                        
Prometheus     2  Adventure,Mystery,Sci-Fi   
Split          3           Horror,Thriller   
Sing           4   Animation,Comedy,Family   

                                                  description  \
Title                                                           
Prometheus  Following clues to the origin of mankind, a te...   
Split       Three girls are kidnapped by a man with a diag...   
Sing        In a city of humanoid animals, a hustling thea...   

                        director  \
Title                              
Prometheus          Ridley Scott   
Split         M. Night Shyamalan   
Sing        Christophe Lourdelet   

                                                       actors  year  runtime  \
Title                                                                          
Prometheus  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012      124   
Split       James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016      117   
Sing        Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016      108   

            rating   votes  revenue_millions  metascore  
Title                                                    
Prometheus     7.0  485820            126.46       65.0  
Split          7.3  157606            138.12       62.0  
Sing           7.2   60545            270.32       59.0

We can also use `.loc` and `.iloc` to access specific columns as well. The way we do this is to use the "second" slot in either `.loc` or `.iloc`.

In [78]:
column_subset = movies_df.loc[:,"genre"]

In [79]:
column_subset

Title
Guardians of the Galaxy     Action,Adventure,Sci-Fi
Prometheus                 Adventure,Mystery,Sci-Fi
Split                               Horror,Thriller
Sing                        Animation,Comedy,Family
Suicide Squad              Action,Adventure,Fantasy
                                     ...           
Secret in Their Eyes            Crime,Drama,Mystery
Hostel: Part II                              Horror
Step Up 2: The Streets          Drama,Music,Romance
Search Party                       Adventure,Comedy
Nine Lives                    Comedy,Family,Fantasy
Name: genre, Length: 1000, dtype: object

In [80]:
column_subset = movies_df.loc[:,"genre":"director"]

In [81]:
column_subset

genre  \
Title                                               
Guardians of the Galaxy   Action,Adventure,Sci-Fi   
Prometheus               Adventure,Mystery,Sci-Fi   
Split                             Horror,Thriller   
Sing                      Animation,Comedy,Family   
Suicide Squad            Action,Adventure,Fantasy   
...                                           ...   
Secret in Their Eyes          Crime,Drama,Mystery   
Hostel: Part II                            Horror   
Step Up 2: The Streets        Drama,Music,Romance   
Search Party                     Adventure,Comedy   
Nine Lives                  Comedy,Family,Fantasy   

                                                               description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   
...                                                                    ...   
Secret in Their Eyes     A tight-knit team of rising investigators, alo...   
Hostel: Part II          Three American college students studying abroa...   
Step Up 2: The Streets   Romantic sparks occur between two dance studen...   
Search Party             A pair of friends embark on a mission to reuni...   
Nine Lives               A stuffy businessman finds himself trapped ins...   

                                     director  
Title                                          
Guardians of the Galaxy            James Gunn  
Prometheus                       Ridley Scott  
Split                      M. Night Shyamalan  
Sing                     Christophe Lourdelet  
Suicide Squad                      David Ayer  
...                                       ...  
Secret in Their Eyes                Billy Ray  
Hostel: Part II                      Eli Roth  
Step Up 2: The Streets             Jon M. Chu  
Search Party                   Scot Armstrong  
Nine Lives                   Barry Sonnenfeld  

[1000 rows x 3 columns]

Notice how we put `:` in the first slot (i.e. before the comma)? This says give us all the rows. Similarly with `.iloc`.

In [82]:
column_subset = movies_df.iloc[:,1]

In [83]:
column_subset

Title
Guardians of the Galaxy     Action,Adventure,Sci-Fi
Prometheus                 Adventure,Mystery,Sci-Fi
Split                               Horror,Thriller
Sing                        Animation,Comedy,Family
Suicide Squad              Action,Adventure,Fantasy
                                     ...           
Secret in Their Eyes            Crime,Drama,Mystery
Hostel: Part II                              Horror
Step Up 2: The Streets          Drama,Music,Romance
Search Party                       Adventure,Comedy
Nine Lives                    Comedy,Family,Fantasy
Name: genre, Length: 1000, dtype: object

In [84]:
column_subset = movies_df.iloc[:,1:4]

In [85]:
column_subset

genre  \
Title                                               
Guardians of the Galaxy   Action,Adventure,Sci-Fi   
Prometheus               Adventure,Mystery,Sci-Fi   
Split                             Horror,Thriller   
Sing                      Animation,Comedy,Family   
Suicide Squad            Action,Adventure,Fantasy   
...                                           ...   
Secret in Their Eyes          Crime,Drama,Mystery   
Hostel: Part II                            Horror   
Step Up 2: The Streets        Drama,Music,Romance   
Search Party                     Adventure,Comedy   
Nine Lives                  Comedy,Family,Fantasy   

                                                               description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   
...                                                                    ...   
Secret in Their Eyes     A tight-knit team of rising investigators, alo...   
Hostel: Part II          Three American college students studying abroa...   
Step Up 2: The Streets   Romantic sparks occur between two dance studen...   
Search Party             A pair of friends embark on a mission to reuni...   
Nine Lives               A stuffy businessman finds himself trapped ins...   

                                     director  
Title                                          
Guardians of the Galaxy            James Gunn  
Prometheus                       Ridley Scott  
Split                      M. Night Shyamalan  
Sing                     Christophe Lourdelet  
Suicide Squad                      David Ayer  
...                                       ...  
Secret in Their Eyes                Billy Ray  
Hostel: Part II                      Eli Roth  
Step Up 2: The Streets             Jon M. Chu  
Search Party                   Scot Armstrong  
Nine Lives                   Barry Sonnenfeld  

[1000 rows x 3 columns]

We can also access a subset of rows and columns _at the same time_.

In [86]:
data_subset = movies_df.loc["Prometheus":"Sing", "genre":"director"]

In [87]:
data_subset

genre  \
Title                                  
Prometheus  Adventure,Mystery,Sci-Fi   
Split                Horror,Thriller   
Sing         Animation,Comedy,Family   

                                                  description  \
Title                                                           
Prometheus  Following clues to the origin of mankind, a te...   
Split       Three girls are kidnapped by a man with a diag...   
Sing        In a city of humanoid animals, a hustling thea...   

                        director  
Title                             
Prometheus          Ridley Scott  
Split         M. Night Shyamalan  
Sing        Christophe Lourdelet

In [88]:
data_subset = movies_df.iloc[1:4, 1:4]

In [89]:
data_subset

genre  \
Title                                  
Prometheus  Adventure,Mystery,Sci-Fi   
Split                Horror,Thriller   
Sing         Animation,Comedy,Family   

                                                  description  \
Title                                                           
Prometheus  Following clues to the origin of mankind, a te...   
Split       Three girls are kidnapped by a man with a diag...   
Sing        In a city of humanoid animals, a hustling thea...   

                        director  
Title                             
Prometheus          Ridley Scott  
Split         M. Night Shyamalan  
Sing        Christophe Lourdelet

## Filtering Data

Often times, we really want to select data based on some condition, or really, to filter it. We can do that with DataFrames quite easily as well. Suppose we only want movies that were directed by Ridley Scott.

In [90]:
movies_df[movies_df['director'] == "Ridley Scott"]

rank                     genre  \
Title                                                    
Prometheus                 2  Adventure,Mystery,Sci-Fi   
The Martian              103    Adventure,Drama,Sci-Fi   
Robin Hood               388    Action,Adventure,Drama   
American Gangster        471     Biography,Crime,Drama   
Exodus: Gods and Kings   517    Action,Adventure,Drama   
The Counselor            522      Crime,Drama,Thriller   
A Good Year              531      Comedy,Drama,Romance   
Body of Lies             738      Action,Drama,Romance   

                                                              description  \
Title                                                                       
Prometheus              Following clues to the origin of mankind, a te...   
The Martian             An astronaut becomes stranded on Mars after hi...   
Robin Hood              In 12th century England, Robin and his band of...   
American Gangster       In 1970s America, a detective works to bring d...   
Exodus: Gods and Kings  The defiant leader Moses rises up against the ...   
The Counselor           A lawyer finds himself in over his head when h...   
A Good Year             A British investment broker inherits his uncle...   
Body of Lies            A CIA agent on the ground in Jordan hunts down...   

                            director  \
Title                                  
Prometheus              Ridley Scott   
The Martian             Ridley Scott   
Robin Hood              Ridley Scott   
American Gangster       Ridley Scott   
Exodus: Gods and Kings  Ridley Scott   
The Counselor           Ridley Scott   
A Good Year             Ridley Scott   
Body of Lies            Ridley Scott   

                                                                   actors  \
Title                                                                       
Prometheus              Noomi Rapace, Logan Marshall-Green, Michael Fa...   
The Martian             Matt Damon, Jessica Chastain, Kristen Wiig, Ka...   
Robin Hood              Russell Crowe, Cate Blanchett, Matthew Macfady...   
American Gangster       Denzel Washington, Russell Crowe, Chiwetel Eji...   
Exodus: Gods and Kings  Christian Bale, Joel Edgerton, Ben Kingsley, S...   
The Counselor           Michael Fassbender, Penélope Cruz, Cameron Dia...   
A Good Year             Russell Crowe, Abbie Cornish, Albert Finney, M...   
Body of Lies            Leonardo DiCaprio, Russell Crowe, Mark Strong,...   

                        year  runtime  rating   votes  revenue_millions  \
Title                                                                     
Prometheus              2012      124     7.0  485820            126.46   
The Martian             2015      144     8.0  556097            228.43   
Robin Hood              2010      140     6.7  221117            105.22   
American Gangster       2007      157     7.8  337835            130.13   
Exodus: Gods and Kings  2014      150     6.0  137299             65.01   
The Counselor           2013      117     5.3   84927             16.97   
A Good Year             2006      117     6.9   74674              7.46   
Body of Lies            2008      128     7.1  182305             39.38   

                        metascore  
Title                              
Prometheus                   65.0  
The Martian                  80.0  
Robin Hood                   53.0  
American Gangster            76.0  
Exodus: Gods and Kings       52.0  
The Counselor                48.0  
A Good Year                  47.0  
Body of Lies                 57.0

What if we want only movies with ratings greater than or equal to 8.6?

In [91]:
movies_df[movies_df['rating'] >= 8.6]

rank                    genre  \
Title                                             
Interstellar        37   Adventure,Drama,Sci-Fi   
The Dark Knight     55       Action,Crime,Drama   
Inception           81  Action,Adventure,Sci-Fi   
Kimi no na wa       97  Animation,Drama,Fantasy   
Dangal             118   Action,Biography,Drama   
The Intouchables   250   Biography,Comedy,Drama   

                                                        description  \
Title                                                                 
Interstellar      A team of explorers travel through a wormhole ...   
The Dark Knight   When the menace known as the Joker wreaks havo...   
Inception         A thief, who steals corporate secrets through ...   
Kimi no na wa     Two strangers find themselves linked in a biza...   
Dangal            Former wrestler Mahavir Singh Phogat and his t...   
The Intouchables  After he becomes a quadriplegic from a paragli...   

                           director  \
Title                                 
Interstellar      Christopher Nolan   
The Dark Knight   Christopher Nolan   
Inception         Christopher Nolan   
Kimi no na wa        Makoto Shinkai   
Dangal                Nitesh Tiwari   
The Intouchables    Olivier Nakache   

                                                             actors  year  \
Title                                                                       
Interstellar      Matthew McConaughey, Anne Hathaway, Jessica Ch...  2014   
The Dark Knight   Christian Bale, Heath Ledger, Aaron Eckhart,Mi...  2008   
Inception         Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...  2010   
Kimi no na wa     Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...  2016   
Dangal            Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...  2016   
The Intouchables  François Cluzet, Omar Sy, Anne Le Ny, Audrey F...  2011   

                  runtime  rating    votes  revenue_millions  metascore  
Title                                                                    
Interstellar          169     8.6  1047747            187.99       74.0  
The Dark Knight       152     9.0  1791916            533.32       82.0  
Inception             148     8.8  1583625            292.57       74.0  
Kimi no na wa         106     8.6    34110              4.68       79.0  
Dangal                161     8.8    48969             11.15        NaN  
The Intouchables      112     8.6   557965             13.18       57.0

Often times we really want to filter by more than one criterion. For example, we might want to get movies that are directed either by Christopher Nolan **or** Ridley Scott. To do an **or** we just connect the conditions by `|`, like below.

In [92]:
movies_df[(movies_df['director'] == 'Christopher Nolan') | (movies_df['director'] == 'Ridley Scott')]

rank                     genre  \
Title                                                    
Prometheus                 2  Adventure,Mystery,Sci-Fi   
Interstellar              37    Adventure,Drama,Sci-Fi   
The Dark Knight           55        Action,Crime,Drama   
The Prestige              65      Drama,Mystery,Sci-Fi   
Inception                 81   Action,Adventure,Sci-Fi   
The Martian              103    Adventure,Drama,Sci-Fi   
The Dark Knight Rises    125           Action,Thriller   
Robin Hood               388    Action,Adventure,Drama   
American Gangster        471     Biography,Crime,Drama   
Exodus: Gods and Kings   517    Action,Adventure,Drama   
The Counselor            522      Crime,Drama,Thriller   
A Good Year              531      Comedy,Drama,Romance   
Body of Lies             738      Action,Drama,Romance   

                                                              description  \
Title                                                                       
Prometheus              Following clues to the origin of mankind, a te...   
Interstellar            A team of explorers travel through a wormhole ...   
The Dark Knight         When the menace known as the Joker wreaks havo...   
The Prestige            Two stage magicians engage in competitive one-...   
Inception               A thief, who steals corporate secrets through ...   
The Martian             An astronaut becomes stranded on Mars after hi...   
The Dark Knight Rises   Eight years after the Joker's reign of anarchy...   
Robin Hood              In 12th century England, Robin and his band of...   
American Gangster       In 1970s America, a detective works to bring d...   
Exodus: Gods and Kings  The defiant leader Moses rises up against the ...   
The Counselor           A lawyer finds himself in over his head when h...   
A Good Year             A British investment broker inherits his uncle...   
Body of Lies            A CIA agent on the ground in Jordan hunts down...   

                                 director  \
Title                                       
Prometheus                   Ridley Scott   
Interstellar            Christopher Nolan   
The Dark Knight         Christopher Nolan   
The Prestige            Christopher Nolan   
Inception               Christopher Nolan   
The Martian                  Ridley Scott   
The Dark Knight Rises   Christopher Nolan   
Robin Hood                   Ridley Scott   
American Gangster            Ridley Scott   
Exodus: Gods and Kings       Ridley Scott   
The Counselor                Ridley Scott   
A Good Year                  Ridley Scott   
Body of Lies                 Ridley Scott   

                                                                   actors  \
Title                                                                       
Prometheus              Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Interstellar            Matthew McConaughey, Anne Hathaway, Jessica Ch...   
The Dark Knight         Christian Bale, Heath Ledger, Aaron Eckhart,Mi...   
The Prestige            Christian Bale, Hugh Jackman, Scarlett Johanss...   
Inception               Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...   
The Martian             Matt Damon, Jessica Chastain, Kristen Wiig, Ka...   
The Dark Knight Rises   Christian Bale, Tom Hardy, Anne Hathaway,Gary ...   
Robin Hood              Russell Crowe, Cate Blanchett, Matthew Macfady...   
American Gangster       Denzel Washington, Russell Crowe, Chiwetel Eji...   
Exodus: Gods and Kings  Christian Bale, Joel Edgerton, Ben Kingsley, S...   
The Counselor           Michael Fassbender, Penélope Cruz, Cameron Dia...   
A Good Year             Russell Crowe, Abbie Cornish, Albert Finney, M...   
Body of Lies            Leonardo DiCaprio, Russell Crowe, Mark Strong,...   

                        year  runtime  rating    votes  revenue_millions  \
Title                                                                      
Prometheus   

Given that we wanted to check whether or not a value was in a set of things (in this case whether or not "director" is in `["Christopher Nolan", "Ridley Scott"]`), we could have done something simpler and used the `.isin()` method.

In [93]:
movies_df[movies_df['director'].isin(['Christopher Nolan', 'Ridley Scott'])]

rank                     genre  \
Title                                                    
Prometheus                 2  Adventure,Mystery,Sci-Fi   
Interstellar              37    Adventure,Drama,Sci-Fi   
The Dark Knight           55        Action,Crime,Drama   
The Prestige              65      Drama,Mystery,Sci-Fi   
Inception                 81   Action,Adventure,Sci-Fi   
The Martian              103    Adventure,Drama,Sci-Fi   
The Dark Knight Rises    125           Action,Thriller   
Robin Hood               388    Action,Adventure,Drama   
American Gangster        471     Biography,Crime,Drama   
Exodus: Gods and Kings   517    Action,Adventure,Drama   
The Counselor            522      Crime,Drama,Thriller   
A Good Year              531      Comedy,Drama,Romance   
Body of Lies             738      Action,Drama,Romance   

                                                              description  \
Title                                                                       
Prometheus              Following clues to the origin of mankind, a te...   
Interstellar            A team of explorers travel through a wormhole ...   
The Dark Knight         When the menace known as the Joker wreaks havo...   
The Prestige            Two stage magicians engage in competitive one-...   
Inception               A thief, who steals corporate secrets through ...   
The Martian             An astronaut becomes stranded on Mars after hi...   
The Dark Knight Rises   Eight years after the Joker's reign of anarchy...   
Robin Hood              In 12th century England, Robin and his band of...   
American Gangster       In 1970s America, a detective works to bring d...   
Exodus: Gods and Kings  The defiant leader Moses rises up against the ...   
The Counselor           A lawyer finds himself in over his head when h...   
A Good Year             A British investment broker inherits his uncle...   
Body of Lies            A CIA agent on the ground in Jordan hunts down...   

                                 director  \
Title                                       
Prometheus                   Ridley Scott   
Interstellar            Christopher Nolan   
The Dark Knight         Christopher Nolan   
The Prestige            Christopher Nolan   
Inception               Christopher Nolan   
The Martian                  Ridley Scott   
The Dark Knight Rises   Christopher Nolan   
Robin Hood                   Ridley Scott   
American Gangster            Ridley Scott   
Exodus: Gods and Kings       Ridley Scott   
The Counselor                Ridley Scott   
A Good Year                  Ridley Scott   
Body of Lies                 Ridley Scott   

                                                                   actors  \
Title                                                                       
Prometheus              Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Interstellar            Matthew McConaughey, Anne Hathaway, Jessica Ch...   
The Dark Knight         Christian Bale, Heath Ledger, Aaron Eckhart,Mi...   
The Prestige            Christian Bale, Hugh Jackman, Scarlett Johanss...   
Inception               Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...   
The Martian             Matt Damon, Jessica Chastain, Kristen Wiig, Ka...   
The Dark Knight Rises   Christian Bale, Tom Hardy, Anne Hathaway,Gary ...   
Robin Hood              Russell Crowe, Cate Blanchett, Matthew Macfady...   
American Gangster       Denzel Washington, Russell Crowe, Chiwetel Eji...   
Exodus: Gods and Kings  Christian Bale, Joel Edgerton, Ben Kingsley, S...   
The Counselor           Michael Fassbender, Penélope Cruz, Cameron Dia...   
A Good Year             Russell Crowe, Abbie Cornish, Albert Finney, M...   
Body of Lies            Leonardo DiCaprio, Russell Crowe, Mark Strong,...   

                        year  runtime  rating    votes  revenue_millions  \
Title                                                                      
Prometheus   

However, often times, we want to combine not just **or** statements or checking whether values are **in** something, but we want to chain together a bunch of filters and check if they all hold. That is an **and** statement and we use `&` to get it. Suppose that we wanted movies released between 2005 and 2010 with a rating above 8.0 but made below the 25th percentile in revenue. We can do this with the below.

In [94]:
movies_df[((movies_df['year'] >= 2005) & (movies_df['year'] <= 2010))
          & (movies_df['rating'] > 8.0)
          & (movies_df['revenue_millions'] < movies_df['revenue_millions'].quantile(0.25))]

rank               genre  \
Title                                           
3 Idiots              431        Comedy,Drama   
The Lives of Others   477      Drama,Thriller   
Incendies             714   Drama,Mystery,War   
Taare Zameen Par      992  Drama,Family,Music   

                                                           description  \
Title                                                                    
3 Idiots             Two friends are searching for their long lost ...   
The Lives of Others  In 1984 East Berlin, an agent of the secret po...   
Incendies            Twins journey to the Middle East to discover t...   
Taare Zameen Par     An eight-year-old boy is thought to be a lazy ...   

                                             director  \
Title                                                   
3 Idiots                              Rajkumar Hirani   
The Lives of Others  Florian Henckel von Donnersmarck   
Incendies                            Denis Villeneuve   
Taare Zameen Par                           Aamir Khan   

                                                                actors  year  \
Title                                                                          
3 Idiots               Aamir Khan, Madhavan, Mona Singh, Sharman Joshi  2009   
The Lives of Others  Ulrich Mühe, Martina Gedeck,Sebastian Koch, Ul...  2006   
Incendies            Lubna Azabal, Mélissa Désormeaux-Poulin, Maxim...  2010   
Taare Zameen Par     Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...  2007   

                     runtime  rating   votes  revenue_millions  metascore  
Title                                                                      
3 Idiots                 170     8.4  238789              6.52       67.0  
The Lives of Others      137     8.5  278103             11.28       89.0  
Incendies                131     8.2   92863              6.86       80.0  
Taare Zameen Par         165     8.5  102697              1.20       42.0

### Problem #3 - 1 point

Create a new dataframe called `chipo_filtered` that consists of all rows where more than one `Chicken Bowl` with the same `choice_description` was ordered. Note that each row corresponds to a particular item with a particular choice description. The `quantity` column denotes how many of that item with that choice description was in the order.

The grade cell will check your answer. If you do not get any errors, you very likely have gotten this question correct. However, there are held back tests as well.

In [121]:
import pandas as pd
import numpy as np
file_path = 'chipotle.tsv'
chipo_df = pd.read_csv(file_path, delimiter='\t')
chicken_bowl_orders = chipo_df[chipo_df['item_name'] == 'Chicken Bowl']
grouped = chicken_bowl_orders.groupby('choice_description')['quantity'].sum().reset_index()
filtered_groups = grouped[grouped['quantity'] > 1]
chipo_filtered = pd.merge(chipo_df, filtered_groups, on='choice_description')
print(chipo_filtered.head())

   order_id  quantity_x      item_name  \
0         2           2   Chicken Bowl   
1       484           1     Steak Bowl   
2       822           1     Steak Bowl   
3         3           1   Chicken Bowl   
4       519           1  Steak Burrito   

                                  choice_description item_price  quantity_y  
0  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98            2  
1  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     $8.99            2  
2  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     $8.99            2  
3  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98            2  
4  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $11.48            2  


In [122]:
# THIS IS A GRADING CELL. DO NOT EDIT AND DO NOT COPY.
# This will give an error if your answer is wrong.
from nose.tools import assert_equal, assert_in
assert_equal(len(chipo_filtered), 33)
assert_equal(chipo_filtered.iloc[3]['quantity'], 3)
assert_equal(chipo_filtered.iloc[24]['order_id'], 1374)

AssertionError: 1085 != 33

## Using `.groupby` to Answer Questions About Groups

A very useful method on dataframes is the `.groupby()` method. `.groupby()` allows you to **group** the data **by** a certain column. This is very similar to a pivot table in excel. Once you have grouped the data, you can do useful operations like find the minimum rating over all movies for a particular directory. First, you need to group the data.

In [123]:
movies_grouped = movies_df.groupby('director')

We can now easily answer questions like, how many directors are in the data set. That is just the length of the `movies_grouped` table, which we can get by this.

In [124]:
len(movies_grouped)

644

Once we have the movies grouped together by `director`, we can pull out individual directors and look at the movies they have worked on.

In [125]:
movies_grouped.get_group('Zack Snyder')

rank                     genre  \
Title                                                                
Batman v Superman: Dawn of Justice    61   Action,Adventure,Sci-Fi   
300                                  114        Action,Fantasy,War   
Watchmen                             148      Action,Drama,Mystery   
Sucker Punch                         286            Action,Fantasy   
Man of Steel                         295  Action,Adventure,Fantasy   

                                                                          description  \
Title                                                                                   
Batman v Superman: Dawn of Justice  Fearing that the actions of Superman are left ...   
300                                 King Leonidas of Sparta and a force of 300 men...   
Watchmen                            In 1985 where former superheroes exist, the mu...   
Sucker Punch                        A young girl is institutionalized by her abusi...   
Man of Steel                        Clark Kent, one of the last of an extinguished...   

                                       director  \
Title                                             
Batman v Superman: Dawn of Justice  Zack Snyder   
300                                 Zack Snyder   
Watchmen                            Zack Snyder   
Sucker Punch                        Zack Snyder   
Man of Steel                        Zack Snyder   

                                                                               actors  \
Title                                                                                   
Batman v Superman: Dawn of Justice  Ben Affleck, Henry Cavill, Amy Adams, Jesse Ei...   
300                                 Gerard Butler, Lena Headey, David Wenham, Domi...   
Watchmen                            Jackie Earle Haley, Patrick Wilson, Carla Gugi...   
Sucker Punch                        Emily Browning, Vanessa Hudgens, Abbie Cornish...   
Man of Steel                        Henry Cavill, Amy Adams, Michael Shannon, Dian...   

                                    year  runtime  rating   votes  \
Title                                                               
Batman v Superman: Dawn of Justice  2016      151     6.7  472307   
300                                 2006      117     7.7  637104   
Watchmen                            2009      162     7.6  410249   
Sucker Punch                        2011      110     6.1  204874   
Man of Steel                        2013      143     7.1  577010   

                                    revenue_millions  metascore  
Title                                                            
Batman v Superman: Dawn of Justice            330.25       44.0  
300                                           210.59       52.0  
Watchmen                                      107.50       56.0  
Sucker Punch                                   36.38       33.0  
Man of Steel                                  291.02       55.0

We can also use methods like `.sum()`, `.min()`, `.max()`, `.median`, `.count()`, and others to get a look into the data. Below we sum up all "summable" columns by each director.

In [126]:
movies_grouped.sum()

rank                                              genre  \
director                                                                       
Aamir Khan            992                                 Drama,Family,Music   
Abdellatif Kechiche   312                                      Drama,Romance   
Adam Leon             784                                     Comedy,Romance   
Adam McKay           1910  Biography,Comedy,DramaComedyAction,Comedy,Crim...   
Adam Shankman        1460            Comedy,Drama,FamilyComedy,Drama,Musical   
...                   ...                                                ...   
Xavier Dolan         1588                                         DramaDrama   
Yimou Zhang             6                           Action,Adventure,Fantasy   
Yorgos Lanthimos      479                 Comedy,Drama,RomanceDrama,Thriller   
Zack Snyder           904  Action,Adventure,Sci-FiAction,Fantasy,WarActio...   
Zackary Adler         605                                        Crime,Drama   

                                                           description  \
director                                                                 
Aamir Khan           An eight-year-old boy is thought to be a lazy ...   
Abdellatif Kechiche  Adèle's life is changed when she meets Emma, a...   
Adam Leon            A young man and woman find love in an unlikely...   
Adam McKay           Four denizens in the world of high-finance pre...   
Adam Shankman        Pleasantly plump teenager Tracy Turnblad teach...   
...                                                                ...   
Xavier Dolan         A widowed single mother, raising her violent s...   
Yimou Zhang          European mercenaries searching for black powde...   
Yorgos Lanthimos     In a dystopian near future, single people, acc...   
Zack Snyder          Fearing that the actions of Superman are left ...   
Zackary Adler        Two brothers unleash a psychotic reign of terr...   

                                                                actors   year  \
director                                                                        
Aamir Khan           Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...   2007   
Abdellatif Kechiche  Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...   2013   
Adam Leon            Callum Turner, Grace Van Patten, Michal Vondel...   2016   
Adam McKay           Christian Bale, Steve Carell, Ryan Gosling, Br...   8039   
Adam Shankman        John Travolta, Queen Latifah, Nikki Blonsky,Mi...   4019   
...                                                                ...    ...   
Xavier Dolan         Anne Dorval, Antoine-Olivier Pilon, Suzanne Cl...   4030   
Yimou Zhang              Matt Damon, Tian Jing, Willem Dafoe, Andy Lau   2016   
Yorgos Lanthimos     Colin Farrell, Rachel Weisz, Jessica Barden,Ol...   4024   
Zack Snyder          Ben Affleck, Henry Cavill, Amy Adams, Jesse Ei...  10055   
Zackary Adler        Matt Vael, Simon Cotton, Kevin Leslie, Olivia ...   2015   

                     runtime  rating    votes  revenue_millions  metascore  
director                                                                    
Aamir Khan               165     8.5   102697              1.20       42.0  
Abdellatif Kechiche      180     7.8   103150              2.20       88.0  
Adam Leon                 82     6.5     1031              0.00       77.0  
Adam McKay               443    28.0   806827            438.14      262.0  
Adam Shankman            240    12.6   167467            157.33      128.0  
...                      ...     ...      ...               ...        ...  
Xavier Dolan             236    15.1    44218              3.49      122.0  
Yimou Zhang              103     6.1    56036             45.13       42.0  
Yorgos Lanthimos         213    14.4   172259              8.81      155.0  
Zack Snyder              683    35.2  2301544            975.74      240.0  
Zackary Adler            110     5.1   

We can then pull out individual directors and see their particular stats.

In [127]:
movies_grouped.sum().loc['Zack Snyder']

rank                                                              904
genre               Action,Adventure,Sci-FiAction,Fantasy,WarActio...
description         Fearing that the actions of Superman are left ...
actors              Ben Affleck, Henry Cavill, Amy Adams, Jesse Ei...
year                                                            10055
runtime                                                           683
rating                                                           35.2
votes                                                         2301544
revenue_millions                                               975.74
metascore                                                       240.0
Name: Zack Snyder, dtype: object

`.sum()` is probably not very useful here. However, we may want to know what Zack Snyder's best rated movie was. We can do that with `.max()`.

In [128]:
movies_grouped.max().loc['Zack Snyder']

rank                                                              295
genre                                              Action,Fantasy,War
description         King Leonidas of Sparta and a force of 300 men...
actors              Jackie Earle Haley, Patrick Wilson, Carla Gugi...
year                                                             2016
runtime                                                           162
rating                                                            7.7
votes                                                          637104
revenue_millions                                               330.25
metascore                                                        56.0
Name: Zack Snyder, dtype: object

You want to be a little careful about interpreting exactly what is going on above. the `.max()` operator is taking the maximum over all columns independently, so Zack Snyder's highest ranked film had a metascore of 56, but the description above is not about this movie. When we looked at all of Zack Snyder's films above, we can see that this metascore was associated with "Watchmen", but the description is of the movie "300".

Often times, we really need to sort the values to answer these questions.

## Sorting Values while Grouping

Dataframes also make sorting easy. Suppose we wanted to quickly answer the question about which of Zack Snyder's movies had the highest metascore, we can first get the group of all of Zack Snyder's movies (like above), and then we can sort by metascore.

In [129]:
movies_grouped.get_group('Zack Snyder').sort_values(by=['metascore'], ascending=False)

rank                     genre  \
Title                                                                
Watchmen                             148      Action,Drama,Mystery   
Man of Steel                         295  Action,Adventure,Fantasy   
300                                  114        Action,Fantasy,War   
Batman v Superman: Dawn of Justice    61   Action,Adventure,Sci-Fi   
Sucker Punch                         286            Action,Fantasy   

                                                                          description  \
Title                                                                                   
Watchmen                            In 1985 where former superheroes exist, the mu...   
Man of Steel                        Clark Kent, one of the last of an extinguished...   
300                                 King Leonidas of Sparta and a force of 300 men...   
Batman v Superman: Dawn of Justice  Fearing that the actions of Superman are left ...   
Sucker Punch                        A young girl is institutionalized by her abusi...   

                                       director  \
Title                                             
Watchmen                            Zack Snyder   
Man of Steel                        Zack Snyder   
300                                 Zack Snyder   
Batman v Superman: Dawn of Justice  Zack Snyder   
Sucker Punch                        Zack Snyder   

                                                                               actors  \
Title                                                                                   
Watchmen                            Jackie Earle Haley, Patrick Wilson, Carla Gugi...   
Man of Steel                        Henry Cavill, Amy Adams, Michael Shannon, Dian...   
300                                 Gerard Butler, Lena Headey, David Wenham, Domi...   
Batman v Superman: Dawn of Justice  Ben Affleck, Henry Cavill, Amy Adams, Jesse Ei...   
Sucker Punch                        Emily Browning, Vanessa Hudgens, Abbie Cornish...   

                                    year  runtime  rating   votes  \
Title                                                               
Watchmen                            2009      162     7.6  410249   
Man of Steel                        2013      143     7.1  577010   
300                                 2006      117     7.7  637104   
Batman v Superman: Dawn of Justice  2016      151     6.7  472307   
Sucker Punch                        2011      110     6.1  204874   

                                    revenue_millions  metascore  
Title                                                            
Watchmen                                      107.50       56.0  
Man of Steel                                  291.02       55.0  
300                                           210.59       52.0  
Batman v Superman: Dawn of Justice            330.25       44.0  
Sucker Punch                                   36.38       33.0

What we did above is we sorted values using `.sort_values()` first `by=['metascore']` and we told it that we wanted values sorted in descending order by setting `ascending=False` (ascending order is the default).

We can combine multiple of these operations to really start to get a good sense for our data. Suppose we wanted to know which director had the highest average metascore, we could use the `.mean()` method on the groups to get the mean of all of the columns by group, and then we can sort by metascore. Again, note the use of `numeric_only=True`.

In [130]:
movies_grouped.mean(numeric_only=True).sort_values(by=['metascore'], ascending=False)

rank    year  runtime  rating     votes  revenue_millions  \
director                                                                       
Barry Jenkins      42.0  2016.0    111.0     7.5  135095.0             27.85   
Kenneth Lonergan   22.0  2016.0    137.0     7.9  134213.0             47.70   
Todd Haynes       502.0  2015.0    118.0     7.2   77995.0              0.25   
Kathryn Bigelow   540.0  2010.0    144.0     7.5  289342.0             55.71   
Michael Goi       634.0  2011.0     85.0     4.9    6683.0               NaN   
...                 ...     ...      ...     ...       ...               ...   
S.S. Rajamouli     27.0  2015.0    159.0     8.3   76193.0              6.50   
Saul Dibb         821.0  2014.0    107.0     6.9   13711.0               NaN   
Shawn Burkett      43.0  2016.0     73.0     2.7     496.0               NaN   
Todor Chapkanov   124.0  2016.0     86.0     7.4   10428.0               NaN   
Warren Beatty     748.0  2016.0    127.0     5.7    3731.0              3.65   

                  metascore  
director                     
Barry Jenkins          99.0  
Kenneth Lonergan       96.0  
Todd Haynes            95.0  
Kathryn Bigelow        94.5  
Michael Goi            94.0  
...                     ...  
S.S. Rajamouli          NaN  
Saul Dibb               NaN  
Shawn Burkett           NaN  
Todor Chapkanov         NaN  
Warren Beatty           NaN  

[644 rows x 7 columns]

It turns out Barry Jenkins has the highest average metascore. Let's see what he made.

In [131]:
movies_grouped.get_group('Barry Jenkins')

rank  genre                                        description  \
Title                                                                       
Moonlight    42  Drama  A chronicle of the childhood, adolescence and ...   

                director                                             actors  \
Title                                                                         
Moonlight  Barry Jenkins  Mahershala Ali, Shariff Earp, Duan Sanderson, ...   

           year  runtime  rating   votes  revenue_millions  metascore  
Title                                                                  
Moonlight  2016      111     7.5  135095             27.85       99.0

Now, let's see which director has made the most movies.

In [132]:
movies_grouped.count().sort_values(by=['year'], ascending=False)

rank  genre  description  actors  year  runtime  rating  \
director                                                                      
Ridley Scott           8      8            8       8     8        8       8   
M. Night Shyamalan     6      6            6       6     6        6       6   
David Yates            6      6            6       6     6        6       6   
Michael Bay            6      6            6       6     6        6       6   
Paul W.S. Anderson     6      6            6       6     6        6       6   
...                  ...    ...          ...     ...   ...      ...     ...   
Ilya Naishuller        1      1            1       1     1        1       1   
Ido Fluk               1      1            1       1     1        1       1   
Hugo Gélin             1      1            1       1     1        1       1   
Hope Dickson Leach     1      1            1       1     1        1       1   
Zackary Adler          1      1            1       1     1        1       1   

                    votes  revenue_millions  metascore  
director                                                
Ridley Scott            8                 8          8  
M. Night Shyamalan      6                 5          6  
David Yates             6                 6          6  
Michael Bay             6                 6          6  
Paul W.S. Anderson      6                 6          6  
...                   ...               ...        ...  
Ilya Naishuller         1                 1          1  
Ido Fluk                1                 0          1  
Hugo Gélin              1                 0          0  
Hope Dickson Leach      1                 0          1  
Zackary Adler           1                 1          1  

[644 rows x 10 columns]

In this dataset, Ridley Scott has made the most movies. Notice we sorted by year because count just counts the values in each column that aren't missing and we just needed something without missing values.

### Problem #4 - 1 point

What is the most ordered item in the dataset? You likely will want to use both `.groupby()` and `.sum()` here. The grade cell will not tell you whether or not you are right. Your answer should look like
``` python
most_ordered = "Item Name Typed Exactly"
```
With `Item Name Typed Exactly` replaced with the exact item name in quotes (and not indented obviously). I.e., if the most common item was `Chips and Fresh Tomato Salsa`, then your answer would look like `most_ordered = "Chips and Fresh Tomato Salsa"`.

In [135]:
import pandas as pd
file_path = 'chipotle.tsv'
chipo_df = pd.read_csv(file_path, delimiter='\t')
items_grouped = chipo_df.groupby('item_name')['quantity'].sum()
most_ordered = items_grouped.idxmax()
most_ordered

'Chicken Bowl'

In [136]:
# THIS IS A GRADING CELL. DO NOT EDIT.
# This cell will not tell you whether or not your answer is right.
# If you have not assigned something to the variable most_ordered or you have not assigned a string,
# you will get an error, but if you just get the question wrong,
# you will not necessarily get an error.
from nose.tools import assert_equal, assert_in
assert_equal(type(most_ordered), str)
print(most_ordered)

Chicken Bowl


### Problem #5 - 1 point

What is the average revenue amount per order? You should assign your answers to the variable `average_revenue`. You can round to the second decimal place (i.e. `10.11` is okay, as is `10.11432` but not `10.1`). The grade cell will not tell you whether or not you are right. Your answer should look something like the below:
``` python
average_revenue = x
```
with x replaced with your answer as a number (and not indented, obviously).

In [137]:
import pandas as pd
file_path = 'chipotle.tsv'
chipo_df = pd.read_csv(file_path, delimiter='\t')
chipo_df['item_price'] = chipo_df['item_price'].str.replace('$', '').astype(float)
order_revenue = chipo_df.groupby('order_id')['item_price'].sum()
average_revenue = order_revenue.mean()
average_revenue = round(average_revenue, 2)
print(average_revenue)

18.81


In [138]:
# THIS IS A GRADING CELL. DO NOT EDIT.
# This cell will not tell you whether or not your answer is right.
# If you have not assigned something to the variable average_revenue or you have not assigned a number,
# you will get an error, but if you just get the question wrong,
# you will not necessarily get an error.
from nose.tools import assert_equal, assert_true
import numbers
assert_true(isinstance(average_revenue, numbers.Number))
print(average_revenue)

18.81
